### ISSUE TITLE
Sonderzeichen (%) in Pfad-Einschränkung führen zu Serverfehler 500

### ISSUE THREAD

**Issue by Ainschy** [terminal42/contao-url-rewrite#4]
Mehr durch Zufall ist eine Kundin beim Erstellen einer Umleitungsregel in diesen Fehler gelaufen.

Sie hatte eine "alte" URL ins Feld Pfad-Einschränkung kopiert: /applikation-kn%C3%B6pfe-bunt.html

Nachdem speichern war die Installation nicht mehr aufrufbar.

`[2018-xx-yy hh:mm:ss] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: "The parameter "c3" must be defined." at /var/customers/webs/XXXXX/isotope/var/cache/prod/appProdProjectContainer.php line 3764 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException(code: 0): The parameter \"c3\" must be defined. at /var/customers/webs/XXXXXX/isotope/var/cache/prod/appProdProjectContainer.php:3764)"} []`

In den Logdateien ließ sich die Quelle für den Fehler nicht ausmachen, erst die Rückfrage ergab Klarheit. Mit dem löschen des Eintrags in der DB war der Fehler behoben.

**Comment by akroii** [comment]
Wenn man versucht von einer aufgerufenen Datei: `Preisliste-Sch%C3%BCtz.pdf` auf eine andere Datei umzuleiten, erhält man im Frontend hinter jedem anklickbaren link ein `%22contao.url_suffix%22`. Das macht natürlich jegliche Navigation unmöglich. Da aus `/shop/preisliste` ein `/shop/preisliste%22contao.url_suffix%22` wird.

Vlt. hängt der Fehler ja zusammen?

**Comment by Toflar** [comment]
`%` should probably be escaped @qzminski

**Comment by qzminski** [comment]
@Ainschy if you define the route with `%` in `config.yml` file then you must escape that character by doubling it `%%`. This cannot be "fixed" in our bundle because it happens at the container configuration level. I have added special note about that in the README in 74b3453.

@akroii although I am unable to reproduce your issue, can you check if 74b3453 does the job? Otherwise please post your complete configuration for this rule and the content element settings (or whatever you use to generate that URL).

**Comment by frontendschlampe** [comment]
@qzminski As I understand, I should escape a `%` with `%%` … but why it's not possible to check the string if there's only one `%` and escape it automatically before save the entry? Or maybe check the string and show an error message to escape it?
